/*
 * Copyright 2026 Spice Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.spicelabs.baharat.pacman;

import io.spicelabs.baharat.common.Dependency;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for Pacman .PKGINFO parsing.
 */
class PacmanReaderTest {

    @Test
    void parsePkgInfo() {
        String pkgInfo = """
                pkgname = nginx
                pkgbase = nginx
                pkgver = 1.24.0-1
                pkgdesc = Lightweight HTTP server
                url = https://nginx.org
                builddate = 1699574400
                packager = Arch Linux Team
                size = 1048576
                arch = x86_64
                license = BSD-2-Clause
                license = MIT
                depend = pcre2
                depend = openssl>=1.1
                provides = httpd
                conflict = nginx-mainline
                replaces = nginx-unstable
                """;

        Map<String, Object> fields = PkgInfoParser.parse(pkgInfo);

        assertThat(fields.get("pkgname")).isEqualTo("nginx");
        assertThat(fields.get("pkgbase")).isEqualTo("nginx");
        assertThat(fields.get("pkgver")).isEqualTo("1.24.0-1");
        assertThat(fields.get("pkgdesc")).isEqualTo("Lightweight HTTP server");
        assertThat(fields.get("url")).isEqualTo("https://nginx.org");
        assertThat(fields.get("size")).isEqualTo("1048576");
        assertThat(fields.get("arch")).isEqualTo("x86_64");

        // Multi-valued fields
        @SuppressWarnings("unchecked")
        List<String> licenses = (List<String>) fields.get("license");
        assertThat(licenses).containsExactly("BSD-2-Clause", "MIT");

        @SuppressWarnings("unchecked")
        List<String> depends = (List<String>) fields.get("depend");
        assertThat(depends).containsExactly("pcre2", "openssl>=1.1");

        @SuppressWarnings("unchecked")
        List<String> provides = (List<String>) fields.get("provides");
        assertThat(provides).containsExactly("httpd");
    }

    @Test
    void parsePkgInfoSkipsComments() {
        String pkgInfo = """
                # Generated by makepkg
                pkgname = test
                # This is a comment
                pkgver = 1.0
                """;

        Map<String, Object> fields = PkgInfoParser.parse(pkgInfo);

        assertThat(fields.get("pkgname")).isEqualTo("test");
        assertThat(fields.get("pkgver")).isEqualTo("1.0");
        assertThat(fields).doesNotContainKey("#");
    }

    @Test
    void pacmanMetadataDependencies() {
        String pkgInfo = """
                pkgname = test
                pkgver = 1.0-1
                arch = x86_64
                depend = openssl>=1.1.0
                depend = pcre2
                depend = zlib<2.0
                makedepend = gcc
                provides = libtest.so
                conflict = test-git
                """;

        Map<String, Object> fields = PkgInfoParser.parse(pkgInfo);
        PacmanMetadata metadata = new PacmanMetadata(fields);

        assertThat(metadata.name()).isEqualTo("test");
        assertThat(metadata.version()).isEqualTo("1.0-1");
        assertThat(metadata.arch()).isEqualTo("x86_64");

        // Check dependencies
        assertThat(metadata.dependencies()).hasSize(3);

        Dependency openssl = metadata.dependencies().stream()
                .filter(d -> d.name().equals("openssl"))
                .findFirst()
                .orElseThrow();
        assertThat(openssl.operator()).isEqualTo(Dependency.Operator.GREATER_THAN_OR_EQUAL);
        assertThat(openssl.version()).contains("1.1.0");

        Dependency zlib = metadata.dependencies().stream()
                .filter(d -> d.name().equals("zlib"))
                .findFirst()
                .orElseThrow();
        assertThat(zlib.operator()).isEqualTo(Dependency.Operator.LESS_THAN);
        assertThat(zlib.version()).contains("2.0");

        // Check provides
        assertThat(metadata.provides())
                .extracting(Dependency::name)
                .contains("libtest.so");

        // Check makedepends
        assertThat(metadata.makedepends())
                .extracting(Dependency::name)
                .contains("gcc");

        // Check conflicts
        assertThat(metadata.conflicts())
                .extracting(Dependency::name)
                .contains("test-git");
    }

    @Test
    void pacmanMetadataBuildTime() {
        String pkgInfo = """
                pkgname = test
                pkgver = 1.0
                arch = x86_64
                builddate = 1699574400
                packager = Test Packager <test@example.org>
                """;

        Map<String, Object> fields = PkgInfoParser.parse(pkgInfo);
        PacmanMetadata metadata = new PacmanMetadata(fields);

        assertThat(metadata.buildTime()).isPresent();
        assertThat(metadata.buildTime().get().getEpochSecond()).isEqualTo(1699574400L);
        assertThat(metadata.maintainer()).contains("Test Packager <test@example.org>");
    }

    @Test
    void pacmanMetadataLicense() {
        String pkgInfo = """
                pkgname = test
                pkgver = 1.0
                arch = any
                license = MIT
                license = Apache-2.0
                """;

        Map<String, Object> fields = PkgInfoParser.parse(pkgInfo);
        PacmanMetadata metadata = new PacmanMetadata(fields);

        assertThat(metadata.license()).contains("MIT, Apache-2.0");
    }
}
