/*
 * Copyright 2026 Spice Labs, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.spicelabs.baharat.apk;

import io.spicelabs.baharat.PackageFormat;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for malformed and invalid APK packages.
 */
class MalformedApkTest {

    @TempDir
    Path tempDir;

    @Test
    void parseEmptyPkgInfo() {
        var fields = ApkInfoParser.parse("");

        assertThat(fields).isEmpty();
    }

    @Test
    void parsePkgInfoWithOnlyComments() {
        var fields = ApkInfoParser.parse("""
                # APK PKGINFO
                # Generated by apk-tools
                """);

        assertThat(fields).isEmpty();
    }

    @Test
    void parsePkgInfoWithInvalidLines() {
        var fields = ApkInfoParser.parse("""
                pkgname = test
                invalid line
                pkgver = 1.0
                """);

        assertThat(fields.get("pkgname")).isEqualTo("test");
        assertThat(fields.get("pkgver")).isEqualTo("1.0");
        assertThat(fields).hasSize(2);
    }

    @Test
    void detectApkFromExtension() throws Exception {
        Path apkFile = tempDir.resolve("test-1.0-r0.apk");
        // Gzip magic bytes (need at least 4 bytes for detection)
        byte[] gzipMagic = {0x1F, (byte) 0x8B, 0x08, 0x00};
        Files.write(apkFile, gzipMagic);

        var format = PackageFormat.detect(apkFile);

        assertThat(format).contains(PackageFormat.APK);
    }

    @Test
    void apkFormatProperties() {
        assertThat(PackageFormat.APK.extension()).isEqualTo(".apk");
        assertThat(PackageFormat.APK.family()).isEqualTo(PackageFormat.Family.LINUX);
        assertThat(PackageFormat.APK.magic()).isPresent();
        // Gzip magic
        assertThat(PackageFormat.APK.magic().get()).isEqualTo(new byte[]{0x1F, (byte) 0x8B});
    }

    @Test
    void metadataWithMissingName() {
        var fields = ApkInfoParser.parse("""
                pkgver = 1.0
                arch = x86_64
                """);

        ApkMetadata metadata = new ApkMetadata(fields);

        assertThat(metadata.name()).isEmpty();
        assertThat(metadata.version()).isEqualTo("1.0");
    }

    @Test
    void metadataWithMissingVersion() {
        var fields = ApkInfoParser.parse("""
                pkgname = test
                arch = x86_64
                """);

        ApkMetadata metadata = new ApkMetadata(fields);

        assertThat(metadata.name()).isEqualTo("test");
        assertThat(metadata.version()).isEmpty();
    }

    @Test
    void metadataWithInvalidSize() {
        var fields = ApkInfoParser.parse("""
                pkgname = test
                pkgver = 1.0
                size = invalid
                """);

        ApkMetadata metadata = new ApkMetadata(fields);

        assertThat(metadata.installedSize()).isEqualTo(0L);
    }

    @Test
    void metadataWithInvalidBuildDate() {
        var fields = ApkInfoParser.parse("""
                pkgname = test
                pkgver = 1.0
                builddate = invalid
                """);

        ApkMetadata metadata = new ApkMetadata(fields);

        assertThat(metadata.buildTime()).isEmpty();
    }

    @Test
    void releaseExtractionEdgeCases() {
        // No release suffix
        var fields1 = ApkInfoParser.parse("pkgname = test\npkgver = 1.0\n");
        ApkMetadata meta1 = new ApkMetadata(fields1);
        assertThat(meta1.release()).isEmpty();

        // Release at the end
        var fields2 = ApkInfoParser.parse("pkgname = test\npkgver = 1.0-r5\n");
        ApkMetadata meta2 = new ApkMetadata(fields2);
        assertThat(meta2.release()).contains("r5");

        // Multiple dashes
        var fields3 = ApkInfoParser.parse("pkgname = test\npkgver = 1.0-alpha-r1\n");
        ApkMetadata meta3 = new ApkMetadata(fields3);
        assertThat(meta3.release()).contains("r1");
    }

    @Test
    void parsePkgInfoLargeFile() {
        StringBuilder sb = new StringBuilder();
        sb.append("pkgname = test\n");
        sb.append("pkgver = 1.0-r0\n");
        for (int i = 0; i < 1000; i++) {
            sb.append("depend = dep").append(i).append("\n");
        }

        var fields = ApkInfoParser.parse(sb.toString());

        assertThat(fields.get("pkgname")).isEqualTo("test");
        @SuppressWarnings("unchecked")
        var depends = (java.util.List<String>) fields.get("depend");
        assertThat(depends).hasSize(1000);
    }
}
