package io.spicelabs.baharat.testdata;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * The expected metadata of every committed test package, one JSON table per fixture directory
 * ({@code src/test/resources/expected/<dir>.json}). The tables are generated by
 * {@link ExpectedPackagesGenerator} from the readers and hand-checked; they are the single
 * definition shared by the unit tests here and by Surveyor's black-box integration tests
 * (surveyor: tests/README.md), which pair their cases with these by the {@code id} field.
 *
 * <p>{@code id} is the package's path under {@code src/test/resources}; {@code tier} is
 * Surveyor's fixture tier (0 = always fetched, 1 = nightly). {@code error} records a
 * package the reader currently rejects, so the failure is visible rather than hidden.
 */
public final class ExpectedPackages {

    public static final Path TABLE_DIR = Path.of("src/test/resources/expected");
    public static final List<String> DIRS = List.of(
            PackageTestFiles.APKS, PackageTestFiles.DEBS, PackageTestFiles.FREEBSD,
            PackageTestFiles.OPENBSD, PackageTestFiles.PACMAN, PackageTestFiles.RPMS);
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().serializeNulls().create();

    private ExpectedPackages() {}

    /** One row of a table. Public fields for Gson; {@code null} means "not asserted". */
    public static final class Expected {
        public String id;
        public String file;
        public String format;
        public int tier = 1;
        public String name;
        public String version;
        public String release;
        public Integer epoch;
        public String arch;
        public String purl;
        public List<String> dependencies;
        public List<String> provides;
        public Integer fileCount;
        public String error;

        public Optional<String> releaseOpt() { return Optional.ofNullable(release); }

        @Override
        public String toString() { return id; }
    }

    public static Path tableFor(String dir) {
        return TABLE_DIR.resolve(dir + ".json");
    }

    /** Rows of the table for one fixture directory (e.g. {@link PackageTestFiles#RPMS}). */
    public static List<Expected> forDir(String dir) throws IOException {
        Path table = tableFor(dir);
        if (!Files.isRegularFile(table)) {
            return List.of();
        }
        try (Reader r = Files.newBufferedReader(table)) {
            List<Expected> rows = GSON.fromJson(r, new TypeToken<List<Expected>>() {}.getType());
            return rows == null ? List.of() : rows;
        }
    }

    /** Every row of every table. */
    public static List<Expected> all() throws IOException {
        List<Expected> out = new ArrayList<>();
        for (String d : DIRS) {
            out.addAll(forDir(d));
        }
        return out;
    }

    /** The row with the given id (e.g. {@code rpms/v4/sed-4.9-1.fc40.x86_64.rpm}). */
    public static Expected of(String id) throws IOException {
        return all().stream().filter(e -> id.equals(e.id)).findFirst()
                .orElseThrow(() -> new AssertionError("no expected row for " + id + " under " + TABLE_DIR));
    }

    /** Absolute path of the package a row describes. */
    public static Path pathOf(Expected e) {
        return Path.of("src/test/resources").resolve(e.id);
    }

    static Gson gson() { return GSON; }
}
